### ISSUE TITLE
Built-in types are highlighted as support.function and not support.type if called

### ISSUE THREAD

**Issue by FichteFoll** [MattDMo/PythonImproved#16]
![2014-09-02_22 40 11](https://cloud.githubusercontent.com/assets/931051/4125367/76fb3c84-32e1-11e4-868e-331a21c42d9f.png)

Consider the above snippets, `str` is once highlighted as `support.type` and once highlighted as `support.function`, as well as `list`. This is probably because they are actually *used like a function*, but in fact they are classes. The default Python syntax def does not treat these built-in type calls differently to the literal references.

Here is the same snippet with the default Python syntax:
![2014-09-02_22 44 56](https://cloud.githubusercontent.com/assets/931051/4125436/11c2c160-32e2-11e4-99d7-ff172942e954.png)

I prefer the default version over the current, but what do you think?

**Comment by aldanor** [comment]
Any updates? :panda_face:

**Comment by MattDMo** [comment]
@aldanor as a matter of fact, yes! PythonImproved 2.0 is going to be released in the very near future, and this is fixed there.

**Comment by aldanor** [comment]
@MattDMo wow, very cool -- and a good timing!

Thanks!
