### ISSUE TITLE
Unicode identifiers are not considered

### ISSUE THREAD

**Issue by FichteFoll** [MattDMo/PythonImproved#19]
As I was made aware by https://github.com/SublimeText/Issues/issues/460, unicode identifiers are currently not considered. The following function call is not recognized as such:

```py
sâomething(arg=22)
```

**Comment by FichteFoll** [comment]
Here is a syntax definition that handles unicode: https://github.com/JoshuaWise/javascript-ultimate

I'm not sure if these are really all the identifiers you need, but they sure ain't little. Would be a nice use case for https://packagecontrol.io/packages/SyntaxHighlightTools because that allows to create some kind of regex repository that you can re-use throughout the whole syntax definition.
([Sadly it doesn't work for me currently.](https://bitbucket.org/klorenz/syntaxhighlighttools/issue/3/building-tmlangtmlang-fails-and-so-do))

**Comment by MattDMo** [comment]
@FichteFoll thanks for the link. I'm reopening this issue for now and removing `wontfix` while I evaluate JS Ultimate and see if we can borrow anything from there.

**Comment by MattDMo** [comment]
OK, so this was surprisingly easy. I replaced `[A-Z_]` with `[\p{Upper}_]`, `[A-Za-z_]` with `[\p{Alpha}_]`, and `[A-Za-z0-9_]` with `[\p{Alnum}_]`, and everything seems to be working well so far. Please clone the repo, switch to the [Unicode](https://github.com/MattDMo/PythonImproved/tree/unicode) branch, put `PythonImproved-Unicode.tmLanguage` in `Packages/PythonImproved` and test it out to see if you can find any bugs. Thanks!

**Comment by FichteFoll** [comment]
Did the replacements in my fork #21 and works pretty well so far.

Details:
I've confirmed that `\x{200C}` and `\x{200D}` are not valid for identifiers (from the JSunl syntax) and not matched by the syntax def. Also `∀`.
I've also conformed that `７` is matched by both Python and the syntax def as a numeric char not-first in an ident. Similarly, full-width alpha stuff like `Ｃ` works like normally.

There might be more special cases, but it worked correctly for everything I tested. Good sign imo.

**Comment by FichteFoll** [comment]
Okay, so according to the reference these are the exact regular expressions for identifiers:

```
[\p{L} \p{Nl} _ 
 \x{2118}\x{212E}\x{309B}\x{309C}]
[\p{L} \p{Nl} _ 
 \x{2118}\x{212E}\x{309B}\x{309C}
 \p{Mn} \x{Mc} \x{Nd} \x{Pc}
 \x{00B7}\x{0387}\x{1369}-\x{1371}\x{19DA}]*
```
(with whitespace stripped, (?x) wouldn't help since that doesn't apply in sets)

Technically `_` could be removed from the second set since it's in `\p{Pc}`, but doesn't matter.

Problem: I don't know how Oniguruma defines `\p{Alpha}` and `\p{Alnum}`.

**Comment by FichteFoll** [comment]
If Oniguruma defines the \p properties in the same way as the POSIX brackets, respectively:
```
alpha    Letter | Mark
word     Letter | Mark | Decimal_Number | Connector_Punctuation
```

and we assume that Letter=\p{L}, Mark=\p{M}, Decimal_Number=\p{Nd} and Connector_Punctuation=\p{Pc}, then we can "shorten" the regex as follows:
```
[[\p{Letter} \p{Nl}  _ 
 \x{2118} \x{212E} \x{309B} \x{309C}] && [^\p{Me}]]
[[\p{Word} \p{Nl} &&[^\p{Me}]
 \x{2118} \x{212E} \x{309B} \x{309C}
 \x{00B7} \x{0387} \x{1369}-\x{1371} \x{19DA}] && [^\p{Me}]]*
```

If `\p{Nl}` also qualifies as "Letter" we could even remove that. `&&[^\p{Me}]` is needed because `\P{Me}` would probably include all but the symbols in Me.

To simplify, use `\p{Word}` for the continuation part instead of `\p{Alnum}_` and we should be fine in 99.999% cases.

**Comment by MattDMo** [comment]
@JoshuaWise got back to me on [JavaScript Ultimate #1](https://github.com/JoshuaWise/javascript-ultimate/issues/1#issuecomment-81476260) and recommended the following (from [here](https://docs.python.org/3/reference/lexical_analysis.html#identifiers)):
```
[A-Za-z_] ?= [\p{Alpha}_]
[\p{L}\p{Nl}_\x{2118}\x{212E}\x{309B}\x{309C}]
 ```
```
[A-Za-z0-9_] ?= [\p{Alnum}_]
[\p{L}\p{Nl}_\x{2118}\x{212E}\x{309B}\x{309C}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\x{1369}\x{00B7}\x{0387}\x{19DA}] 
```
```
[A-Z_] ?= [\p{Upper}_]
[\p{Lu}\p{Lt}\p{Lo}\p{Lm}\p{Nl}_\x{2118}\x{212E}\x{309B}\x{309C}] 
```
```
[A-Z0-9_] ?= [\p{Upper}\p{Digit}_]
[\p{Lu}\p{Lt}\p{Lo}\p{Lm}\p{Nl}_\x{2118}\x{212E}\x{309B}\x{309C}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\x{1369}\x{00B7}\x{0387}\x{19DA}]
```
I'll double-check these, but the main question is still: is `[\p{Alpha}_]` equivalent to `[\p{L}\p{Nl}_\x{2118}\x{212E}\x{309B}\x{309C}]` and all the rest? I can certainly go through and change everything (again), but it makes the regexes much harder to understand. I'm planning on asking on the forum if anyone has any experience with this, but it's down right now - go figure. Do any of you know of any resources where we can get a selection of characters from each class (`\p{Lu}`, `\p{Lt}`, etc.) and test them against the current `\p{Alpha}`, `\p{Alnum}`, etc. regexes?

**Comment by FichteFoll** [comment]
I feel slightly ignored.

Anyway, I highly doubt `\p{Alpha}` would include the special characters that Python allows (for legacy reasons I think). Besides, they will hardly get used at any point. If you are willing to sacrifice a bit of accuracy in favor of readability of the expressions, I suggest the following based on my previous comment:

```
[A-Za-z_] => [\p{Letter}\p{Nl}_]
[A-Z0-9a-z_] => [[\p{Word}\p{Nl}]&&[^\p{Me}]]
[A-Z_] => [\p{Upper}_]  (is only used for the constants in caps so an optional feature anyway)
[A-Z0-9_] => [\p{Upper}\p{Nl}\p{Nd}\p{Pc}] (see above)
```

I would be interested in the exact representations of `\p{Letter}`, `\p{Word}` and `\p{Alnum}` though.

**Comment by MattDMo** [comment]
@FichteFoll that looks like a good idea. Hopefully we can find/develop a decent test suite to make sure everything works. And don't worry, I'm not ignoring you :grinning:

**Comment by MattDMo** [comment]
@FichteFoll so I'm getting ready to release PI 2.0 (finally) and I came back across this issue. I had been using `[\p{Alpha}_][\p{Alnum}_]*` as my "identifier" regex in the unicode branch, but the more I think about it, I'd rather be too narrow than too broad, so I'm going to use your suggestions:
```
[\p{Alpha}_] => [\p{Letter}\p{Nl}_]
[\p{Alnum}_] => [[\p{Word}\p{Nl}]&&[^\p{Me}]]
[\p{Upper}_] (already using) 
[\p{Upper}\p{Digit}_] => [\p{Upper}\p{Nl}\p{Nd}\p{Pc}]
```
It's not as visually pleasing as `Alpha` and `Alnum`, but seeing as we don't know the exact definition of those classes, I'd rather be safe than sorry and use what you came up with.

**Comment by MattDMo** [comment]
Alrighty then:
```
error: Error loading syntax file "Packages/Python Improved/PythonImproved.tmLanguage": 
Error in regex: invalid character property name {Letter} in regex \b(?i:(((\d+(\.(?=[^\p{Letter}\p{Nl}_])\d*)?|(?<=[^\p{Alnum}_])\.\d+)(e[\-\+]?\d+)?))J)
```

So I guess it's back to `[\p{Alpha}_][\p{Alnum}_]*` for now...
