### ISSUE TITLE
Raw string support

### ISSUE THREAD

**Issue by RazerM** [MattDMo/PythonImproved#25]
Raw strings have the same formatting as normal strings, so backslashes are incorrectly interpreted as escapes, for example:

![image](https://cloud.githubusercontent.com/assets/1337586/6021022/91a53874-abb2-11e4-959d-3714d0c5827e.png)

It would be useful if raw strings didn't highlight escapes differently.

**Comment by MattDMo** [comment]
Good point. I'm in the middle of a bunch of changes, so I'll throw this in there too. Thanks!

**Comment by facelessuser** [comment]
As I recall, raw strings are often used for regex, so the regex highlighter kicks in and that is why escapes are highlighted.  As far as I can tell, there is no way to distinguish a raw string that is not meant for regex from a raw string meant for regex.  I personally prefer having the escaped chars to no regex highlighting.

**Comment by MattDMo** [comment]
Another good point. I'll look at exactly how the regexes work - there might be a way to exclude `#escaped_chars` and still include the escapes defined in `source.regex.python`. I'm at work now, so I can't look ATM...

**Comment by FichteFoll** [comment]
By coincidence I found out that this is "fixed" already (as it was in the original Python syntax):

![2015-03-08_19 38 32](https://cloud.githubusercontent.com/assets/931051/6547024/d5e7c736-c5ca-11e4-8376-158528be3460.png)

**Comment by MattDMo** [comment]
As it turns out, while adding an uppercase `R` will remove regex highlighting, the `R` is now scoped as a constant instead of `storage.type.string.python`. I'll see if I can fix this.

**Comment by MattDMo** [comment]
I'll be releasing 2.1 soon. With it, you can now (again) use `R"..."` to designate raw strings with no regex highlighting, while `r"..."` should retain the old behavior.
