### ISSUE TITLE
Greedy error scope

### ISSUE THREAD

**Issue by cknv** [MattDMo/PythonImproved#31]
I noted that when using errors (catching, raising, all that) that are inside a module the scoping turn out to be quite wide. Say you have this snippet:

```python
import mymodule
mymodule.WhoaError
```

Currently, the whole second line would be scoped with `support.type.exception.python`, and not only the part behind the dot, which was what I initially expected.

I am not sure if I think it makes sense.. I mean.. I can see both sides of the argument, scoping the whole thing vs scoping just the error (and not the module it came from), but I wanted to point it out to you if it was not a deliberate decision.

If you want to change it, I do believe that it would be `[.a-zA-Z0-9_]+` on line [470](https://github.com/MattDMo/PythonImproved/blob/master/PythonImproved.YAML-tmLanguage#L470) that should be changed to `[a-zA-Z0-9_]+`, perhaps in both locations.

I noted that it is actually showcased on the Neon screenshot on [packagecontrol.io](https://packagecontrol.io/packages/Neon%20Color%20Scheme), look for `except picke.PickleError as p_err`.

**Comment by MattDMo** [comment]
It's a remnant of the original language definition (I just tweaked it to display custom errors as well), but I hadn't really thought about whether it makes sense to just highlight the error, or the whole module. I'm leaning towards leaving it as is, as there conceivably could be situations where you have an identically-named error in two or more different modules, and the current highlighting stresses the originating module as well as the error. However, I'll leave this open for a bit and see if anyone has other ideas or feedback.

**Comment by FichteFoll** [comment]
Fixed in #17 btw.

**Comment by FichteFoll** [comment]
Personally, I like it the way it currently is.

**Comment by MattDMo** [comment]
I can't remember when I pushed the fix, but the 2.0 release just highlights the Error/Warning/Exception part, not the parent module:

<img width="158" alt="screen shot 2015-12-04 at 10 23 20 am" src="https://cloud.githubusercontent.com/assets/1776358/11593257/4e2cf72c-9a71-11e5-8648-6d6b3a7850f5.png">
