### ISSUE TITLE
SublimeLinter-pep8 and SublimeLinter-flake8 do not work

### ISSUE THREAD

**Issue by rexdf** [MattDMo/PythonImproved#36]
SublimeLinter-pep8 and SublimeLinter-flake8 do not work.
If disable this plugin, then both work.

**Comment by brianpiper** [comment]
You may want to try this, I had the same issue for a bit. Go to the package settings for SublimeLinter, and modify the syntax map so that `pythonimproved` mode is mapped to the `python` linters, like this:

            "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python" # <-- This is the new line!
        },

That might help.

**Comment by rexdf** [comment]
Thx. It does work.

**Comment by gjcarneiro** [comment]
This bug was closed without any action, yet I have myself spent a lot of time until I found this bug.

At least, can we add a note to the README?

**Comment by MattDMo** [comment]
I personally don't use SublimeLinter (I much prefer [`Anaconda`](https://packagecontrol.io/packages/Anaconda)), so this wasn't really on my radar. Feel free to fork the repo and submit a pull request with the changes and explanation(s) you'd like to see, and I'll merge it in.

**Comment by MattDMo** [comment]
This has been merged into SublimeLinter3/master.
