### ISSUE TITLE
PythonImproved and SublimeLinter

### ISSUE THREAD

**Issue by dbrattli** [MattDMo/PythonImproved#37]
Had a hard time getting flake8 linter working. Turned out the problem was that I was using PythonImproved and the linter framework ignored the file. To enable you must make a syntax mapping [1] from `pythonimproved` to `python` in user settings of `SublimeLinter.sublime-settings`:

        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python"
        },

Would be nice if this could be added to the docs since others are likely to experience the same problem.

[1] http://www.sublimelinter.com/en/latest/global_settings.html#syntax-map

**Comment by dbrattli** [comment]
Duplicate of #14

**Comment by rexdf** [comment]
Duplicate of #36

**Comment by kiddick** [comment]
Same here. Hard to find out.
