### ISSUE TITLE
2.0 won't build!

### ISSUE THREAD

**Issue by MattDMo** [MattDMo/PythonImproved#46]
So we've got a big problem. I've pushed all my changes to the `unicode` branch so you can check them out. Converting from `YAML-tmLanguage` to `tmLanguage` goes fine, but as soon as I move the new file to my `Packages/Python Improved` directory, I get this in the console:

```
[PackageDev] File conversion successful. (yaml -> plist)
error parsing lexer: Packages/Python Improved/PythonImproved-Unicode.tmLanguage: boost::bad_any_cast: failed conversion using boost::any_cast
generating syntax summary
reloading /C/Users/mmorrison/Dropbox/Sublime/ST3_WinXP/Packages/Python Improved/PythonImproved-Unicode.tmLanguage
```

*Any* pointers at all will be helpful. I just want to get this thing out!

**Comment by facelessuser** [comment]
What was the last revision that worked?  It is hard to go through line by line and figure this out, but if you can tell us which commit started to not load, it would be easier to troubleshoot.

**Comment by facelessuser** [comment]
I figured it out.  I'll post the answer probably tomorrow when I have time.

**Comment by facelessuser** [comment]
Pull #49 will fix the load issue.

**Comment by MattDMo** [comment]
Isaac, you are fantastic! This release is dedicated to you!
