### ISSUE TITLE
class behavior modifiers

### ISSUE THREAD

**Issue by apetri** [MattDMo/PythonImproved#51]
Thank you guys for all your great work! I just wanted to point out this issue: class behavior modifier highlighting stopped working (i.e. __init__, __enter__, etc... are now highlighted as normal methods), see image below
![screen shot 2015-11-03 at 10 17 48 am](https://cloud.githubusercontent.com/assets/3975482/10911786/7634dfb6-8214-11e5-89b1-73d5d5904823.png)

**Comment by MattDMo** [comment]
Hi Andrea,
Thank you for the feedback. Somehow this slipped through my testing, thanks for catching it! I *think* this should be a relatively easy fix, but I'll need to look into it first.

**Comment by MattDMo** [comment]
Here you go:

<img width="677" alt="screen shot 2015-12-04 at 12 41 44 pm" src="https://cloud.githubusercontent.com/assets/1776358/11596664/71a48496-9a84-11e5-890d-1b5c5941beb1.png">
