### ISSUE TITLE
Using `cls` as a function breaks highlighting for arguments

### ISSUE THREAD

**Issue by aldanor** [MattDMo/PythonImproved#52]
This is a quite common snippet:

```python
@classmethod
def from_foo(cls, foo):
    return cls(foo, bar='baz')
```

However it breaks highlighting for arguments inside `()` since `cls` is not treated as a function.

**Comment by MattDMo** [comment]
Thanks for the feedback, I'll take a look and see what I can do.

**Comment by MattDMo** [comment]
@aldanor just so I'm sure on what I need to fix - can `self` also be a function like `cls`? If so, I can just modify them both at the same time.

**Comment by aldanor** [comment]
@MattDMo yea it could be, in case `__call__` is implemented. But `cls` is always callable, so there's that

**Comment by MattDMo** [comment]
Thanks for your help! I fixed the argument highlighting fixed:

<img width="265" alt="screen shot 2015-12-04 at 8 37 53 pm" src="https://cloud.githubusercontent.com/assets/1776358/11605192/065574aa-9ac7-11e5-975b-17beec6aaf32.png">

**Comment by aldanor** [comment]
Thanks!

**Comment by vaultah** [comment]
Is this by design?

![](http://i.imgur.com/U8cTG8m.png?1)

**Comment by MattDMo** [comment]
Umm ... nope. Back to work...

**Comment by MattDMo** [comment]
<img width="272" alt="screen shot 2015-12-05 at 2 16 59 pm" src="https://cloud.githubusercontent.com/assets/1776358/11609665/eb7d11e4-9b5a-11e5-90be-f80bd0502e8b.png">

**Comment by aldanor** [comment]
@MattDMo 

Another bug, it seems:

![image](https://cloud.githubusercontent.com/assets/2418513/11627897/dbf02126-9ce5-11e5-9c21-c0780c0723e1.png)

**Comment by MattDMo** [comment]
Just pushed release 2.1.2, which fixes this:

<img width="281" alt="screen shot 2015-12-07 at 1 44 58 pm" src="https://cloud.githubusercontent.com/assets/1776358/11636203/dc1b8f48-9ce8-11e5-831a-1e887de79a4c.png">

I missed a word delimiter (`\b`) in one or two spots. Everything *should* work as expected now.
