### ISSUE TITLE
3 dots are highlighted as Ellipsis when part of import statements

### ISSUE THREAD

**Issue by vaultah** [MattDMo/PythonImproved#53]
Well, here's the picture:

![](http://i.imgur.com/kzAoZnL.png)

**Comment by MattDMo** [comment]
Thanks for the feedback. This should be relatively easy to fix.

**Comment by MattDMo** [comment]
This should be addressed in [this commit](https://github.com/MattDMo/PythonImproved/commit/20971710b1b3816872e6807b85e790362cc0a0f4#diff-4d42c1fbc2cee9ab2d185c611139962fR11).
