### ISSUE TITLE
The return statement is sometimes highlighted as function call

### ISSUE THREAD

**Issue by vaultah** [MattDMo/PythonImproved#55]
Welp, the title says it all. Some examples:

![](http://i.imgur.com/JmF6tly.png?1)

**Comment by MattDMo** [comment]
Good grief. One bug at a time!

**Comment by vaultah** [comment]
Also, same for `yield` :p

**Comment by MattDMo** [comment]
That's it, you're cut off!
:warning: :fu:

**Comment by MattDMo** [comment]
This is related to #52, which has now been fixed.
