### ISSUE TITLE
Compatibility with Visual Studio Code

### ISSUE THREAD

**Issue by nchammas** [MattDMo/PythonImproved#57]
[Visual Studio Code](https://github.com/Microsoft/vscode) currently uses TextMate for syntax highlighting of Python, which is [broken in many ways](https://github.com/Microsoft/vscode/issues/1467). Also, the TextMate Python package hasn't seen a commit since mid-2014, so it does not appear to be maintained either.

According to [this comment](https://github.com/textmate/python.tmbundle/issues/43#issuecomment-68200599), this project may be a better replacement for TextMate for syntax highlighting in VS Code.

Does that sound about right to the maintainers of this project?

**Comment by MattDMo** [comment]
Hi Nicholas,
I'm very sorry for the late reply. I have absolutely no issue whatsoever with Python Improved being used as the default Python syntax for VSCode, as long as the MIT license and my name are included. I replied to your issue in the VSCode repo as well. Let's keep this thread open for discussing implementation details as needed, or for preparing PI for the VSCode store in case that's a better option.

**Comment by nchammas** [comment]
Closing this since VS Code has moved on from TextMate. I'm not sure where exactly VS Code stands today as far as Python syntax highlighting, but I know it works much better than when I filed this report. I assume the maintainers of this project can pursue VS Code integration independent of this issue.
