### ISSUE TITLE
Syntax is a bit out of date

### ISSUE THREAD

**Issue by dactylo** [MattDMo/PythonImproved#61]
With the recent update to ST3 I've switched back to using the default syntax file, with my own corrections. But before that, I noticed that PythonImproved is also a bit out of date.

Here's a patch for the default:
https://forum.sublimetext.com/t/updated-sublime-syntax-for-python/18123

**Comment by MattDMo** [comment]
Could you please provide some additional details, with examples, of how Python Improved is "out of date"? It is purposely compatible with both Python 3 and Python 2, which would cover many of the changes in your patch.

**Comment by dactylo** [comment]
Okay, since I use the latest stable version of 3, I'd prefer not to have stuff highlighted as builtins that are no longer builtins in that version, or are really types. One example would be "file" but there are several others.

**Comment by MattDMo** [comment]
Unfortunately, Python 2 is not going away any time soon. Even though official support for the language is ending in 2020, there are tons of projects with legacy code that still need to be supported. While it would be theoretically possible for me to separate out the Python 2 content in PI from the Python 3, along with a common core, it's not something I'm interested in architecting right now.
