### ISSUE TITLE
Error with backslash at end of raw string

### ISSUE THREAD

**Issue by escalonn** [MattDMo/PythonImproved#65]
This code is parsed wrongly (line 421):
![](https://i.gyazo.com/d80e767debf199e13941627ad8df66cd.png)

Any time a raw string (whether introduced with `r` or `R`) ends with `\`, the backslash is treated as though it escapes the following string-ending quotation mark. The rest of the code is then highlighted wrongly: with Neon here, it is italicized and the colors are wrong.

**Comment by MattDMo** [comment]
This is very much related to #34. Basically, the solution is to switch to the `sublime-syntax` format, as it really can't be addressed by the regexes in `.tmLanguage` files.
